services:
    - type: web
    name: roar-crew-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
            - key: DISCORD_TOKEN
        sync: false
            - key: PORT
        value: 10000
